title: Anton Nazarov | Software Engineer  # You can add your name here

description: Keep this world simple # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin
