title: Anton Nazarov | Software Engineer  # You can add your name here

logo: 1.png # Use a relative path to logo image 

description: Keep this world simple # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin
